services:
  pegasus-plus:
    image: ghcr.io/dafrenchyman/pegasus-plus:v0.1.0
    container_name: pegasus-plus
    restart: unless-stopped
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Etc/UTC"
    volumes:
      - ./local-data/roms:/ROMs
      - ./local-data/bioses:/bioses
      - ./local-data/home:/home/retro
    devices:
      - "nvidia.com/gpu=all"
    privileged: true
