apiVersion: v2
name: docling-serve
description: A Helm chart for Docling-Serve, an API service wrapper for AI document conversion
type: application
kubeVersion: ">=1.19.0-0"
keywords:
  - docling
  - document-conversion
  - ai
  - pdf
  - api
  - fastapi
maintainers:
  - name: julien-pierret
    email: julien.pierret@gmail.com
home: https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/docling-serve
sources:
  - https://github.com/khwong-c/helm-charts/tree/main/charts/docling-serve
  - https://github.com/docling-project/docling-serve
  - https://github.com/docling-project/docling
  - https://github.com/dafrenchyman/dockers_and_helm
icon:
version: 0.1.2
appVersion: "1.9.0"
