apiVersion: v2
name: comfyui
description: ComfyUI with baked ComfyUI-Manager and ComfyUI-Sentinel
type: application
kubeVersion: ">=1.24.0-0"
maintainers:
- name: julien-pierret
  email: julien.pierret@gmail.com
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts/
    version: 4.3.0
home: https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/comfyui
sources:
  - https://github.com/comfyanonymous/ComfyUI
  - https://github.com/Comfy-Org/ComfyUI-Manager
  - https://github.com/LucipherDev/ComfyUI-Sentinel
  - https://github.com/dafrenchyman/dockers_and_helm
  - https://bjw-s-labs.github.io/helm-charts/
icon:
version: 0.1.2
appVersion: v0.18.0
