#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  games:
    enabled: false
    mountPath: /games

ps3netsrv:
  image:
    # -- bluecherryServer image repository
    repository: shawly/ps3netsrv
    # -- bluecherryServer image tag
    tag: v1.6.0
    # -- bluecherryServer image pull policy
    pullPolicy: Always
  # -- UID to run bluecherry user as. If you want to access recordings from the host, it is recommended to set them the same as a user/group that you want access to read it. run `id $(whoami)` to find the UID/GID of your user
  uid: "1000"
  # -- GID to run bluecherry user as. If you want to access recordings from the host, it is recommended to set them the same as a user/group that you want access to read it. run `id $(whoami)` to find the UID/GID of your user
  gid: "1000"
  # -- bluecherryServer image timezone
  timezone: America/Los_Angeles

mkgamedirectories:
  image:
    # -- image repository
    repository: busybox
    # -- image tag
    tag: 1.34.0
    # -- image pull policy
    pullPolicy: IfNotPresent

service:
  main:
    enabled: false
  games:
    enabled: true
    type: NodePort
    ports:
      games-tcp:
        enabled: true
        port: 38008
        protocol: TCP
        targetPort: 38008
      games-udp:
        enabled: true
        port: 38008
        protocol: UDP
        targetPort: 38008
    externalTrafficPolicy: Local
