apiVersion: v1
entries:
  ambient-weather-prometheus-exporter:
    - apiVersion: v2
      appVersion: 1.0.0
      created: "2025-10-11T17:23:53.976454707-07:00"
      dependencies:
        - name: common
          repository: https://library-charts.k8s-at-home.com
          version: 4.0.1
      description: Prometheus metric exporter for Ambient Weather Stations
      digest: e316442ecd1a60574d3e93398d1d9c9f600a4aa66345533d1bb671d28bd820c7
      home: https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/ambient-weather-prometheus-exporter
      keywords:
        - ambient weather
      kubeVersion: ">=1.16.0-0"
      maintainers:
        - email: julien.pierret@gmail.com
          name: julien-pierret
      name: ambient-weather-prometheus-exporter
      sources:
        - https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/ambient-weather-prometheus-exporter
        - https://github.com/dafrenchyman/dockers_and_helm/tree/master/containers/ambient-weather-prometheus-exporter
      urls:
        - https://charts.mrsharky.com/ambient-weather-prometheus-exporter-0.1.0.tgz
      version: 0.1.0
  bluecherry:
    - apiVersion: v2
      appVersion: 1.0.0
      created: "2025-10-11T17:23:53.977621656-07:00"
      dependencies:
        - name: common
          repository: https://library-charts.k8s-at-home.com
          version: 4.2.0
      description: Bluecherry DVR
      digest: 56ce8568a0833092a629286cf4899cc4d2b40600cb93fc5d9b8b3ff69c933b83
      home: https://www.bluecherrydvr.com/
      keywords:
        - bluecherry
      kubeVersion: ">=1.16.0-0"
      maintainers:
        - email: julien.pierret@gmail.com
          name: julien-pierret
      name: bluecherry
      sources:
        - https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/bluecherry
        - https://github.com/dafrenchyman/dockers_and_helm/tree/master/containers/bluecherry-server
        - https://github.com/bluecherrydvr/bluecherry-docker
        - https://hub.docker.com/r/dafrenchyman/bluecherry-server
      urls:
        - https://charts.mrsharky.com/bluecherry-0.1.0.tgz
      version: 0.1.0
  dropbox:
    - apiVersion: v2
      appVersion: 1.10.0
      created: "2025-10-11T17:23:53.978687872-07:00"
      dependencies:
        - name: common
          repository: https://library-charts.k8s-at-home.com
          version: 4.0.1
      description: Run Dropbox service
      digest: 4630bb4aafeb2c4716e075b0f88a0826abc68de78ca9cfceec1936d4798a1d31
      home: https://github.com/otherguy/docker-dropbox
      keywords:
        - dropbox
      kubeVersion: ">=1.16.0-0"
      maintainers:
        - email: julien.pierret@gmail.com
          name: julien-pierret
      name: dropbox
      sources:
        - https://github.com/otherguy/docker-dropbox
        - https://hub.docker.com/r/otherguy/dropbox
      urls:
        - https://charts.mrsharky.com/dropbox-0.1.0.tgz
      version: 0.1.0
  kavita:
    - apiVersion: v2
      appVersion: 0.4.8
      created: "2025-10-11T17:23:53.979847366-07:00"
      dependencies:
        - name: common
          repository: https://library-charts.k8s-at-home.com
          version: 4.0.1
      description: Kavita is a fast, feature rich, cross platform OSS manga server.
      digest: 1ccf26b1971f9742d4ebad3ee1feecd2beb4623b42f146c916a4518dc1a27415
      home: https://www.kavitareader.com/
      keywords:
        - kavita
      kubeVersion: ">=1.16.0-0"
      maintainers:
        - email: julien.pierret@gmail.com
          name: julien-pierret
      name: kavita
      sources:
        - https://github.com/Kareadita/Kavita
        - https://hub.docker.com/r/kizaing/kavita
      urls:
        - https://charts.mrsharky.com/kavita-0.1.0.tgz
      version: 0.1.0
  nzbget-exporter:
    - apiVersion: v2
      appVersion: 0.1.0
      created: "2025-10-11T17:23:53.982668855-07:00"
      dependencies:
        - name: common
          repository: https://bjw-s-labs.github.io/helm-charts/
          version: 4.3.0
      description: NZBget Prometheus Exporter
      digest: d44ff5e805e05746b546052a697a28ebe3f834d6460c3fc5e29cf5fee77c1683 # pragma: allowlist secret
      home: https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/nzbget-exporter
      kubeVersion: ">=1.24.0-0"
      maintainers:
        - email: julien.pierret@gmail.com
          name: julien-pierret
      name: nzbget-exporter
      sources:
        - https://github.com/frebib/nzbget-exporter
        - https://bjw-s-labs.github.io/helm-charts/
      type: application
      urls:
        - https://charts.mrsharky.com/nzbget-exporter-0.1.0.tgz
      version: 0.1.0
  ps3netsrv:
    - apiVersion: v2
      appVersion: 1.0.0
      created: "2025-10-11T17:23:53.983805706-07:00"
      dependencies:
        - name: common
          repository: https://library-charts.k8s-at-home.com
          version: 4.2.0
      description: ps3netsrv
      digest: 26d165134e9bae0ceee39c9817494cb6c4a3cc24492e1c15b234e2a4e65c2c2f # pragma: allowlist secret
      home: https://github.com/aldostools/ps3netsrv-go
      keywords:
        - ps3netsrv
        - ps3
      kubeVersion: ">=1.16.0-0"
      maintainers:
        - email: julien.pierret@gmail.com
          name: julien-pierret
      name: ps3netsrv
      sources:
        - https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/ps3netsrv
        - https://hub.docker.com/r/shawly/ps3netsrv/
        - https://github.com/shawly/docker-ps3netsrv
        - https://github.com/aldostools/ps3netsrv-go
      urls:
        - https://charts.mrsharky.com/ps3netsrv-0.1.0.tgz
      version: 0.1.0
  redash:
    - apiVersion: v1
      appVersion: 10.0.0.b50633
      created: "2025-10-11T17:23:54.000383012-07:00"
      dependencies:
        - condition: redis.enabled
          name: redis
          repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
          version: ^10.8.2
        - condition: postgresql.enabled
          name: postgresql
          repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
          version: ^8.10.14
      description:
        Redash is an open source tool built for teams to query, visualize
        and collaborate.
      digest: 223227a968b7924d56bdeb861680816998270d30b138080b2e2cd3f4ef7bd5a1 # pragma: allowlist secret
      home: https://redash.io/
      icon: https://redash.io/assets/images/elements/redash-logo.svg
      keywords:
        - redash
        - analytics
        - visualization
      maintainers:
        - email: owen.barton@civicactions.com
          name: Owen Barton
      name: redash
      sources:
        - https://github.com/getredash/redash
      urls:
        - https://charts.mrsharky.com/redash-3.0.2.tgz
      version: 3.0.2
    - apiVersion: v1
      appVersion: 10.0.0.b50633
      created: "2025-10-11T17:23:53.995771576-07:00"
      dependencies:
        - condition: redis.enabled
          name: redis
          repository: https://charts.bitnami.com/bitnami
          version: ^16.12.1
        - condition: postgresql.enabled
          name: postgresql
          repository: https://charts.bitnami.com/bitnami
          version: ^11.6.2
      description:
        Redash is an open source tool built for teams to query, visualize
        and collaborate.
      digest: efae0afd44334127240601cb23b7889e9cd3f8564da6a0e34871fce6bced1504 # pragma: allowlist secret
      home: https://redash.io/
      icon: https://redash.io/assets/images/elements/redash-logo.svg
      keywords:
        - redash
        - analytics
        - visualization
      maintainers:
        - email: owen.barton@civicactions.com
          name: Owen Barton
      name: redash
      sources:
        - https://github.com/getredash/redash
      urls:
        - https://charts.mrsharky.com/redash-3.0.1.tgz
      version: 3.0.1
    - apiVersion: v1
      appVersion: 10.0.0.b50633
      created: "2025-10-11T17:23:53.989199115-07:00"
      dependencies:
        - condition: redis.enabled
          name: redis
          repository: https://charts.bitnami.com/bitnami
          version: ^16.12.1
        - condition: postgresql.enabled
          name: postgresql
          repository: https://charts.bitnami.com/bitnami
          version: ^11.6.2
      description:
        Redash is an open source tool built for teams to query, visualize
        and collaborate.
      digest: 0f4cecbb49c9379473312c908d8b9bb6ef8b3c2dae333b2f4faa264cf9542966 # pragma: allowlist secret
      home: https://redash.io/
      icon: https://redash.io/assets/images/elements/redash-logo.svg
      keywords:
        - redash
        - analytics
        - visualization
      maintainers:
        - email: owen.barton@civicactions.com
          name: Owen Barton
      name: redash
      sources:
        - https://github.com/getredash/redash
      urls:
        - https://charts.mrsharky.com/redash-3.0.0.tgz
      version: 3.0.0
  termix:
    - apiVersion: v2
      appVersion: 0.1.0
      created: "2025-10-11T17:23:54.003088079-07:00"
      dependencies:
        - name: common
          repository: https://bjw-s-labs.github.io/helm-charts/
          version: 4.3.0
      description: Termix
      digest: c9ad9f2dcf846785fe33fceaf596c17b9fe0d4222e052eeb1b48b612807254df # pragma: allowlist secret
      home: https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/termix
      kubeVersion: ">=1.24.0-0"
      maintainers:
        - email: julien.pierret@gmail.com
          name: julien-pierret
      name: termix
      sources:
        - https://github.com/LukeGus/Termix?tab=readme-ov-file
        - https://bjw-s-labs.github.io/helm-charts/
      type: application
      urls:
        - https://charts.mrsharky.com/termix-0.1.0.tgz
      version: 0.1.0
  ubooquity:
    - apiVersion: v2
      appVersion: version-2.1.2
      created: "2025-10-11T17:23:54.004313038-07:00"
      dependencies:
        - name: common
          repository: https://library-charts.k8s-at-home.com
          version: 4.0.1
      description:
        Ubooquity is a free, lightweight and easy-to-use home server for
        your comics and ebooks. Use it to access your files from anywhere, with a tablet,
        an e-reader, a phone or a computer.
      digest: dd7a9f238b34ef3369959c99a0f649bb14c9800b3d4df4402a76c8254f0adcf3
      home: https://github.com/dafrenchyman/dockers_and_helm/tree/master/charts/ubooquity
      keywords:
        - ubooquity
      kubeVersion: ">=1.16.0-0"
      maintainers:
        - email: julien.pierret@gmail.com
          name: julien-pierret
      name: ubooquity
      sources:
        - https://hub.docker.com/r/linuxserver/ubooquity
      urls:
        - https://charts.mrsharky.com/ubooquity-0.1.0.tgz
      version: 0.1.0
generated: "2025-10-11T17:23:53.975079681-07:00"
