---
{{- include "bjw-s.common.loader.init" . }}

{{- define "comfyui.hardcodedValues" -}}
{{- if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{- end }}
{{- end -}}

{{- $_ := mergeOverwrite .Values (include "comfyui.hardcodedValues" . | fromYaml) -}}
{{- $_ := mergeOverwrite .Values (((include "comfyui.defaults.controller" .) | fromYaml) | default (dict)) -}}
{{- $_ := mergeOverwrite .Values (((include "comfyui.defaults.podOptions" .) | fromYaml) | default (dict)) -}}

{{ include "bjw-s.common.loader.generate" . }}
