---

#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# -- This is the default, you can also use requarks/wiki
image:
  # -- image repository
  repository: ghcr.io/linuxserver/ubooquity
  # -- image tag
  tag: version-2.1.2
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-ubooquity#environment-variables-e) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Set UserID
  PUID: "1001"
  # -- Set GroupID
  PGID: "1001"
  # -- To set the maximum memory. ( ex: set '1024' for 1GB )
  # MAXMEM: 100

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 2202
  admin:
    enabled: true
    ports:
      admin:
        enabled: true
        port: 2203


ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /config
  books:
    enabled: false
    mountPath: /books
  comics:
    enabled: false
    mountPath: /comics
