{{- if and (eq .Values.computeEngine.type "rq") (not .Values.redis.external.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docling-serve.fullname" . }}-redis
  labels:
    {{- include "docling-serve.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "docling-serve.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
