apiVersion: v1
kind: Service
metadata:
  name: {{ include "docling-serve.fullname" . }}
  labels:
    {{- include "docling-serve.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.env.uvicorn.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "docling-serve.selectorLabels" . | nindent 4 }}
